language: node_js

node_js:
  - "0.8"
  - "0.10"

services:
  - mongodb
  - redis-server
  - mysql

before_script:
  - npm install sails-mysql sails-mongo sails-redis
  - mysql -e "create database waterline;"

notifications:
    irc: "irc.freenode.org#sailsjs"
